services:
  # --- BANCO DE DADOS (PostgreSQL) ---
  db:
    image: postgres:15-alpine
    container_name: factory-db
    environment:
      POSTGRES_USER: factory_admin
      POSTGRES_PASSWORD: factory_password
      POSTGRES_DB: factory_erp_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # --- BACKEND (Quarkus) ---
  backend:
    build: ./backend
    container_name: factory-api
    ports:
      - "8080:8080"
    environment:
      
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/factory_erp_db
      QUARKUS_DATASOURCE_USERNAME: factory_admin
      QUARKUS_DATASOURCE_PASSWORD: factory_password
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: drop-and-create
      QUARKUS_HIBERNATE_ORM_SQL_LOAD_SCRIPT: import.sql
      QUARKUS_HTTP_CORS: "true"
      QUARKUS_HTTP_CORS_ORIGINS: "*"
    depends_on:
      - db

  # --- FRONTEND (React) ---
  frontend:
    build: ./frontend
    container_name: factory-ui
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata: